import { StateNode, District, PHCCentre, EarlyWarningAlert, RedistributionTransfer, OutbreakScenario, FederatedTrainingRound } from '../types';

export const INITIAL_STATES: StateNode[] = [
  {
    code: 'MH',
    name: 'Maharashtra',
    capital: 'Mumbai',
    totalPhcs: 3240,
    monitoredCohortPhcs: 28,
    populationServedMillions: 112.4,
    essentialStockIndexPercent: 89.2,
    averageBufferDays: 22.4,
    coldChainCompliancePercent: 96.8,
    activeDoctorAttendancePercent: 93.5,
    activeCriticalAlerts: 2,
    federatedWeightVersion: 'v4.18-MH',
    federatedLoss: 0.042,
    privacyBudgetEpsilon: 0.85,
    color: '#0284c7',
  },
  {
    code: 'UP',
    name: 'Uttar Pradesh',
    capital: 'Lucknow',
    totalPhcs: 4560,
    monitoredCohortPhcs: 36,
    populationServedMillions: 235.6,
    essentialStockIndexPercent: 84.1,
    averageBufferDays: 16.8,
    coldChainCompliancePercent: 92.4,
    activeDoctorAttendancePercent: 89.2,
    activeCriticalAlerts: 4,
    federatedWeightVersion: 'v4.18-UP',
    federatedLoss: 0.058,
    privacyBudgetEpsilon: 0.92,
    color: '#f59e0b',
  },
  {
    code: 'TN',
    name: 'Tamil Nadu',
    capital: 'Chennai',
    totalPhcs: 2680,
    monitoredCohortPhcs: 24,
    populationServedMillions: 76.8,
    essentialStockIndexPercent: 94.6,
    averageBufferDays: 28.5,
    coldChainCompliancePercent: 98.9,
    activeDoctorAttendancePercent: 96.1,
    activeCriticalAlerts: 1,
    federatedWeightVersion: 'v4.18-TN',
    federatedLoss: 0.029,
    privacyBudgetEpsilon: 0.74,
    color: '#10b981',
  },
  {
    code: 'KL',
    name: 'Kerala',
    capital: 'Thiruvananthapuram',
    totalPhcs: 1420,
    monitoredCohortPhcs: 16,
    populationServedMillions: 35.1,
    essentialStockIndexPercent: 96.8,
    averageBufferDays: 31.2,
    coldChainCompliancePercent: 99.4,
    activeDoctorAttendancePercent: 97.4,
    activeCriticalAlerts: 1,
    federatedWeightVersion: 'v4.18-KL',
    federatedLoss: 0.021,
    privacyBudgetEpsilon: 0.68,
    color: '#06b6d4',
  },
  {
    code: 'RJ',
    name: 'Rajasthan',
    capital: 'Jaipur',
    totalPhcs: 2850,
    monitoredCohortPhcs: 22,
    populationServedMillions: 79.5,
    essentialStockIndexPercent: 82.4,
    averageBufferDays: 15.3,
    coldChainCompliancePercent: 90.1,
    activeDoctorAttendancePercent: 88.0,
    activeCriticalAlerts: 3,
    federatedWeightVersion: 'v4.18-RJ',
    federatedLoss: 0.062,
    privacyBudgetEpsilon: 0.89,
    color: '#f97316',
  },
  {
    code: 'AS',
    name: 'Assam',
    capital: 'Dispur',
    totalPhcs: 1340,
    monitoredCohortPhcs: 14,
    populationServedMillions: 34.2,
    essentialStockIndexPercent: 81.5,
    averageBufferDays: 14.1,
    coldChainCompliancePercent: 88.6,
    activeDoctorAttendancePercent: 86.4,
    activeCriticalAlerts: 3,
    federatedWeightVersion: 'v4.18-AS',
    federatedLoss: 0.067,
    privacyBudgetEpsilon: 0.95,
    color: '#8b5cf6',
  },
  {
    code: 'OD',
    name: 'Odisha',
    capital: 'Bhubaneswar',
    totalPhcs: 1980,
    monitoredCohortPhcs: 18,
    populationServedMillions: 44.9,
    essentialStockIndexPercent: 87.3,
    averageBufferDays: 19.6,
    coldChainCompliancePercent: 93.2,
    activeDoctorAttendancePercent: 91.0,
    activeCriticalAlerts: 2,
    federatedWeightVersion: 'v4.18-OD',
    federatedLoss: 0.048,
    privacyBudgetEpsilon: 0.81,
    color: '#ec4899',
  },
];

export const INITIAL_DISTRICTS: District[] = [
  // Maharashtra
  { id: 'DIST-MH-PUN', stateCode: 'MH', name: 'Pune', headquarters: 'Pune', population: '9.4M', phcsCount: 96, status: 'Nominal', avgBufferDays: 24.5 },
  { id: 'DIST-MH-GAD', stateCode: 'MH', name: 'Gadchiroli', headquarters: 'Gadchiroli', population: '1.1M', phcsCount: 48, status: 'Warning', avgBufferDays: 12.4, topShortageDrug: 'Polyvalent Antivenom' },
  // Uttar Pradesh
  { id: 'DIST-UP-GKP', stateCode: 'UP', name: 'Gorakhpur', headquarters: 'Gorakhpur', population: '4.5M', phcsCount: 112, status: 'Critical', avgBufferDays: 8.9, topShortageDrug: 'Ceftriaxone & Antipyretics' },
  { id: 'DIST-UP-VNS', stateCode: 'UP', name: 'Varanasi', headquarters: 'Varanasi', population: '3.7M', phcsCount: 84, status: 'Nominal', avgBufferDays: 21.0 },
  // Tamil Nadu
  { id: 'DIST-TN-MDU', stateCode: 'TN', name: 'Madurai', headquarters: 'Madurai', population: '3.1M', phcsCount: 78, status: 'Nominal', avgBufferDays: 32.0 },
  { id: 'DIST-TN-NIL', stateCode: 'TN', name: 'Nilgiris', headquarters: 'Udhagamandalam', population: '0.7M', phcsCount: 32, status: 'Warning', avgBufferDays: 14.5, topShortageDrug: 'Rabies Vaccine & Inhalers' },
  // Kerala
  { id: 'DIST-KL-WYD', stateCode: 'KL', name: 'Wayanad', headquarters: 'Kalpetta', population: '0.8M', phcsCount: 30, status: 'Warning', avgBufferDays: 16.2, topShortageDrug: 'Doxycycline & ORS' },
  { id: 'DIST-KL-PLK', stateCode: 'KL', name: 'Palakkad', headquarters: 'Palakkad', population: '2.8M', phcsCount: 65, status: 'Nominal', avgBufferDays: 29.4 },
  // Rajasthan
  { id: 'DIST-RJ-BRM', stateCode: 'RJ', name: 'Barmer', headquarters: 'Barmer', population: '2.6M', phcsCount: 72, status: 'Critical', avgBufferDays: 7.8, topShortageDrug: 'IV Normal Saline & ORS' },
  { id: 'DIST-RJ-JOD', stateCode: 'RJ', name: 'Jodhpur', headquarters: 'Jodhpur', population: '3.7M', phcsCount: 88, status: 'Nominal', avgBufferDays: 22.8 },
  // Assam
  { id: 'DIST-AS-MAJ', stateCode: 'AS', name: 'Majuli', headquarters: 'Garamur', population: '0.2M', phcsCount: 18, status: 'Critical', avgBufferDays: 6.2, topShortageDrug: 'Artemether & Water Purifier Tabs' },
  { id: 'DIST-AS-KAM', stateCode: 'AS', name: 'Kamrup', headquarters: 'Amingaon', population: '1.5M', phcsCount: 62, status: 'Nominal', avgBufferDays: 20.4 },
  // Odisha
  { id: 'DIST-OD-MAY', stateCode: 'OD', name: 'Mayurbhanj', headquarters: 'Baripada', population: '2.5M', phcsCount: 74, status: 'Warning', avgBufferDays: 13.5, topShortageDrug: 'Polyvalent Antivenom & IFA' },
  { id: 'DIST-OD-GNJ', stateCode: 'OD', name: 'Ganjam', headquarters: 'Chhatrapur', population: '3.5M', phcsCount: 82, status: 'Nominal', avgBufferDays: 24.1 },
];

export const INITIAL_PHCS: PHCCentre[] = [
  {
    id: 'PHC-MH-BHOR',
    code: 'PHC-MH-27041',
    name: 'PHC Bhor',
    districtId: 'DIST-MH-PUN',
    districtName: 'Pune',
    stateCode: 'MH',
    stateName: 'Maharashtra',
    tier: 'Primary Health Centre (PHC)',
    terrain: 'Hilly / Ghats',
    coordinates: { lat: 18.156, lng: 73.847 },
    connectivity: 'Online',
    lastSyncTime: 'Just now (Synced)',
    powerSource: 'Dual Solar Grid + Battery',
    activeAlertsCount: 1,
    footfall: {
      opdToday: 142,
      emergencyAdmissions: 6,
      feverOutbreakCases: 28,
      highRiskAntenatal: 11,
      historical7Days: [118, 122, 130, 125, 138, 140, 142],
    },
    beds: {
      generalTotal: 12,
      generalOccupied: 9,
      maternalTotal: 6,
      maternalOccupied: 4,
      oxygenTotal: 4,
      oxygenOccupied: 2,
      pediatricTotal: 4,
      pediatricOccupied: 3,
      emergencyTotal: 2,
      emergencyOccupied: 1,
    },
    personnel: [
      { role: 'Medical Officer (MBBS)', sanctioned: 2, present: 2, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Dr. Anand Kulkarni' },
      { role: 'Staff Nurse', sanctioned: 4, present: 3, onFieldOutreach: 1, onLeave: 0, biometricVerified: true, shiftLead: 'Sunita Gaikwad' },
      { role: 'Auxiliary Nurse Midwife (ANM)', sanctioned: 6, present: 3, onFieldOutreach: 3, onLeave: 0, biometricVerified: true, shiftLead: 'Pooja Jadhav' },
      { role: 'Pharmacist', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Ramesh Patil' },
      { role: 'Lab Technician', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Meera Deshmukh' },
    ],
    medicineInventory: [
      {
        id: 'MED-MH-01',
        medicineName: 'Polyvalent Snake Antivenom (Lyophilized)',
        genericName: 'Anti-snake venom serum (Indian 4-species)',
        category: 'Emergency / Antivenom',
        currentStock: 14,
        unitType: 'Vials',
        minimumSafetyBuffer: 30,
        dailyBurnRate: 3.4,
        projectedDaysRemaining: 4.1,
        batchNumber: 'ASV-2026-B812',
        expiryDate: '2027-11-30',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 4.2,
        coldChainOk: true,
        status: 'Low Stock',
      },
      {
        id: 'MED-MH-02',
        medicineName: 'Amoxicillin + Clavulanic Acid 625mg',
        genericName: 'Amoxicillin and Potassium Clavulanate',
        category: 'Antibiotic',
        currentStock: 480,
        unitType: 'Tablets',
        minimumSafetyBuffer: 350,
        dailyBurnRate: 42,
        projectedDaysRemaining: 11.4,
        batchNumber: 'AMC-9904',
        expiryDate: '2028-02-15',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 22.1,
        coldChainOk: true,
        status: 'Adequate',
      },
      {
        id: 'MED-MH-03',
        medicineName: 'Covaxin / Adult Booster Vaccine',
        genericName: 'Whole-Virion Inactivated Corona Vaccine',
        category: 'Vaccine',
        currentStock: 120,
        unitType: 'Vials',
        minimumSafetyBuffer: 80,
        dailyBurnRate: 8,
        projectedDaysRemaining: 15.0,
        batchNumber: 'BBV-7711',
        expiryDate: '2027-06-30',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 3.8,
        coldChainOk: true,
        status: 'Adequate',
      },
      {
        id: 'MED-MH-04',
        medicineName: 'Oxytocin Injection 5 IU/ml',
        genericName: 'Oxytocin synthetic ampoules',
        category: 'Maternal Health',
        currentStock: 65,
        unitType: 'Ampoules',
        minimumSafetyBuffer: 50,
        dailyBurnRate: 4.5,
        projectedDaysRemaining: 14.4,
        batchNumber: 'OXY-4102',
        expiryDate: '2027-09-15',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 4.6,
        coldChainOk: true,
        status: 'Adequate',
      },
      {
        id: 'MED-MH-05',
        medicineName: 'Normal Saline (0.9% NaCl) 500ml',
        genericName: 'Sodium Chloride IV Infusion',
        category: 'IV Fluids',
        currentStock: 110,
        unitType: 'Bottles',
        minimumSafetyBuffer: 150,
        dailyBurnRate: 18,
        projectedDaysRemaining: 6.1,
        batchNumber: 'NS-8841',
        expiryDate: '2028-10-31',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 30°C',
        currentStorageTemp: 23.5,
        coldChainOk: true,
        status: 'Low Stock',
      },
      {
        id: 'MED-MH-06',
        medicineName: 'Metformin Hydrochloride 500mg',
        genericName: 'Metformin Extended Release',
        category: 'Chronic / NCD',
        currentStock: 1850,
        unitType: 'Tablets',
        minimumSafetyBuffer: 1200,
        dailyBurnRate: 75,
        projectedDaysRemaining: 24.6,
        batchNumber: 'MET-2026-03',
        expiryDate: '2028-05-30',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 22.0,
        coldChainOk: true,
        status: 'Surplus',
      },
    ],
  },
  {
    id: 'PHC-UP-CHAURI',
    code: 'PHC-UP-09112',
    name: 'PHC Chauri Chaura',
    districtId: 'DIST-UP-GKP',
    districtName: 'Gorakhpur',
    stateCode: 'UP',
    stateName: 'Uttar Pradesh',
    tier: 'Community Health Centre (CHC)',
    terrain: 'Plains',
    coordinates: { lat: 26.645, lng: 83.585 },
    connectivity: 'Online',
    lastSyncTime: '3 mins ago',
    powerSource: 'State Grid with Diesel Generator',
    activeAlertsCount: 2,
    footfall: {
      opdToday: 235,
      emergencyAdmissions: 14,
      feverOutbreakCases: 64,
      highRiskAntenatal: 18,
      historical7Days: [180, 195, 210, 205, 225, 230, 235],
    },
    beds: {
      generalTotal: 24,
      generalOccupied: 22,
      maternalTotal: 10,
      maternalOccupied: 9,
      oxygenTotal: 8,
      oxygenOccupied: 7,
      pediatricTotal: 10,
      pediatricOccupied: 10,
      emergencyTotal: 4,
      emergencyOccupied: 4,
    },
    personnel: [
      { role: 'Medical Officer (MBBS)', sanctioned: 4, present: 3, onFieldOutreach: 1, onLeave: 0, biometricVerified: true, shiftLead: 'Dr. Vivek Srivastava' },
      { role: 'Staff Nurse', sanctioned: 8, present: 7, onFieldOutreach: 1, onLeave: 0, biometricVerified: true, shiftLead: 'Rani Kumari' },
      { role: 'Auxiliary Nurse Midwife (ANM)', sanctioned: 12, present: 5, onFieldOutreach: 7, onLeave: 0, biometricVerified: true, shiftLead: 'Anjali Sharma' },
      { role: 'Pharmacist', sanctioned: 2, present: 2, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'S. N. Tiwari' },
      { role: 'Lab Technician', sanctioned: 2, present: 2, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Gyanendra Pal' },
    ],
    medicineInventory: [
      {
        id: 'MED-UP-01',
        medicineName: 'Ceftriaxone 1g Injection',
        genericName: 'Ceftriaxone Sodium Sterile Vials',
        category: 'Antibiotic',
        currentStock: 35,
        unitType: 'Vials',
        minimumSafetyBuffer: 150,
        dailyBurnRate: 24,
        projectedDaysRemaining: 1.4,
        batchNumber: 'CTX-1109',
        expiryDate: '2027-08-31',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 24.2,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-UP-02',
        medicineName: 'Paracetamol 250mg/5ml Pediatric Syrup',
        genericName: 'Paracetamol Oral Suspension',
        category: 'Antibiotic',
        currentStock: 60,
        unitType: 'Bottles',
        minimumSafetyBuffer: 200,
        dailyBurnRate: 35,
        projectedDaysRemaining: 1.7,
        batchNumber: 'PCM-4421',
        expiryDate: '2028-01-10',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 24.5,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-UP-03',
        medicineName: 'Artemether + Lumefantrine 80/480mg',
        genericName: 'Artemisinin Combination Therapy',
        category: 'Antimalarial',
        currentStock: 180,
        unitType: 'Tablets',
        minimumSafetyBuffer: 250,
        dailyBurnRate: 28,
        projectedDaysRemaining: 6.4,
        batchNumber: 'ACT-7712',
        expiryDate: '2027-10-15',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 24.0,
        coldChainOk: true,
        status: 'Low Stock',
      },
      {
        id: 'MED-UP-04',
        medicineName: 'Normal Saline (0.9% NaCl) 500ml',
        genericName: 'Sodium Chloride IV Infusion',
        category: 'IV Fluids',
        currentStock: 80,
        unitType: 'Bottles',
        minimumSafetyBuffer: 250,
        dailyBurnRate: 45,
        projectedDaysRemaining: 1.7,
        batchNumber: 'NS-9912',
        expiryDate: '2028-11-20',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 30°C',
        currentStorageTemp: 25.1,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-UP-05',
        medicineName: 'Measles-Rubella (MR) Vaccine',
        genericName: 'Live Attenuated MR Vaccine with Diluent',
        category: 'Vaccine',
        currentStock: 210,
        unitType: 'Vials',
        minimumSafetyBuffer: 150,
        dailyBurnRate: 12,
        projectedDaysRemaining: 17.5,
        batchNumber: 'MR-5520',
        expiryDate: '2027-04-30',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 4.8,
        coldChainOk: true,
        status: 'Adequate',
      },
    ],
  },
  {
    id: 'PHC-TN-GUDALUR',
    code: 'PHC-TN-33019',
    name: 'PHC Gudalur',
    districtId: 'DIST-TN-NIL',
    districtName: 'Nilgiris',
    stateCode: 'TN',
    stateName: 'Tamil Nadu',
    tier: 'Primary Health Centre (PHC)',
    terrain: 'Remote Tribal',
    coordinates: { lat: 11.503, lng: 76.492 },
    connectivity: 'Intermittent 2G',
    lastSyncTime: '42 mins ago',
    powerSource: 'Dual Solar Grid + Battery',
    activeAlertsCount: 1,
    footfall: {
      opdToday: 98,
      emergencyAdmissions: 5,
      feverOutbreakCases: 16,
      highRiskAntenatal: 8,
      historical7Days: [82, 85, 90, 88, 92, 95, 98],
    },
    beds: {
      generalTotal: 10,
      generalOccupied: 7,
      maternalTotal: 4,
      maternalOccupied: 3,
      oxygenTotal: 4,
      oxygenOccupied: 2,
      pediatricTotal: 4,
      pediatricOccupied: 2,
      emergencyTotal: 2,
      emergencyOccupied: 1,
    },
    personnel: [
      { role: 'Medical Officer (MBBS)', sanctioned: 2, present: 2, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Dr. Priya Varma' },
      { role: 'Staff Nurse', sanctioned: 4, present: 3, onFieldOutreach: 1, onLeave: 0, biometricVerified: true, shiftLead: 'Kalaivani M' },
      { role: 'Auxiliary Nurse Midwife (ANM)', sanctioned: 5, present: 2, onFieldOutreach: 3, onLeave: 0, biometricVerified: true, shiftLead: 'Revathi S' },
      { role: 'Pharmacist', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'K. Murugan' },
      { role: 'Lab Technician', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Deepa R' },
    ],
    medicineInventory: [
      {
        id: 'MED-TN-01',
        medicineName: 'Anti-Rabies Vaccine (Cell Culture)',
        genericName: 'Purified Chick Embryo Cell Vaccine',
        category: 'Vaccine',
        currentStock: 8,
        unitType: 'Vials',
        minimumSafetyBuffer: 40,
        dailyBurnRate: 3.8,
        projectedDaysRemaining: 2.1,
        batchNumber: 'ARV-3310',
        expiryDate: '2027-07-31',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 3.9,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-TN-02',
        medicineName: 'Salbutamol + Ipratropium Respules',
        genericName: 'Bronchodilator Nebulizer Solution',
        category: 'Emergency / Antivenom',
        currentStock: 45,
        unitType: 'Ampoules',
        minimumSafetyBuffer: 80,
        dailyBurnRate: 9,
        projectedDaysRemaining: 5.0,
        batchNumber: 'SAL-1288',
        expiryDate: '2028-03-31',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 19.8,
        coldChainOk: true,
        status: 'Low Stock',
      },
      {
        id: 'MED-TN-03',
        medicineName: 'Iron & Folic Acid (IFA) Tablets',
        genericName: 'Ferrous Sulfate 100mg + Folic Acid 0.5mg',
        category: 'Maternal Health',
        currentStock: 2400,
        unitType: 'Tablets',
        minimumSafetyBuffer: 1500,
        dailyBurnRate: 65,
        projectedDaysRemaining: 36.9,
        batchNumber: 'IFA-9921',
        expiryDate: '2028-12-31',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 30°C',
        currentStorageTemp: 20.2,
        coldChainOk: true,
        status: 'Surplus',
      },
      {
        id: 'MED-TN-04',
        medicineName: 'Polyvalent Snake Antivenom (Lyophilized)',
        genericName: 'Anti-snake venom serum (Indian 4-species)',
        category: 'Emergency / Antivenom',
        currentStock: 32,
        unitType: 'Vials',
        minimumSafetyBuffer: 25,
        dailyBurnRate: 1.8,
        projectedDaysRemaining: 17.7,
        batchNumber: 'ASV-TN-102',
        expiryDate: '2027-10-31',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 4.1,
        coldChainOk: true,
        status: 'Adequate',
      },
    ],
  },
  {
    id: 'PHC-RJ-SHEO',
    code: 'PHC-RJ-08034',
    name: 'PHC Sheo (Thar Desert)',
    districtId: 'DIST-RJ-BRM',
    districtName: 'Barmer',
    stateCode: 'RJ',
    stateName: 'Rajasthan',
    tier: 'Primary Health Centre (PHC)',
    terrain: 'Arid / Desert',
    coordinates: { lat: 26.183, lng: 71.246 },
    connectivity: 'Offline',
    lastSyncTime: '3 hours ago (Local Queue: 5 txns)',
    powerSource: 'Solar Micro-Array',
    activeAlertsCount: 2,
    footfall: {
      opdToday: 110,
      emergencyAdmissions: 9,
      feverOutbreakCases: 32,
      highRiskAntenatal: 7,
      historical7Days: [80, 85, 94, 98, 102, 108, 110],
    },
    beds: {
      generalTotal: 8,
      generalOccupied: 8,
      maternalTotal: 4,
      maternalOccupied: 3,
      oxygenTotal: 2,
      oxygenOccupied: 2,
      pediatricTotal: 3,
      pediatricOccupied: 3,
      emergencyTotal: 2,
      emergencyOccupied: 2,
    },
    personnel: [
      { role: 'Medical Officer (MBBS)', sanctioned: 2, present: 1, onFieldOutreach: 1, onLeave: 0, biometricVerified: true, shiftLead: 'Dr. Mahendra Bishnoi' },
      { role: 'Staff Nurse', sanctioned: 3, present: 3, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Santosh Devi' },
      { role: 'Auxiliary Nurse Midwife (ANM)', sanctioned: 6, present: 2, onFieldOutreach: 4, onLeave: 0, biometricVerified: true, shiftLead: 'Kiran Rathore' },
      { role: 'Pharmacist', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'G. L. Meena' },
      { role: 'Lab Technician', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Narendra Singh' },
    ],
    medicineInventory: [
      {
        id: 'MED-RJ-01',
        medicineName: 'Normal Saline (0.9% NaCl) 500ml',
        genericName: 'Sodium Chloride IV Infusion',
        category: 'IV Fluids',
        currentStock: 22,
        unitType: 'Bottles',
        minimumSafetyBuffer: 120,
        dailyBurnRate: 26,
        projectedDaysRemaining: 0.8,
        batchNumber: 'NS-DES-411',
        expiryDate: '2028-09-30',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 35°C',
        currentStorageTemp: 31.4,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-RJ-02',
        medicineName: 'Oral Rehydration Salts (WHO Formula)',
        genericName: 'ORS Sachets 20.5g',
        category: 'IV Fluids',
        currentStock: 75,
        unitType: 'Bottles',
        minimumSafetyBuffer: 300,
        dailyBurnRate: 65,
        projectedDaysRemaining: 1.1,
        batchNumber: 'ORS-6610',
        expiryDate: '2028-06-30',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 30°C',
        currentStorageTemp: 30.5,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-RJ-03',
        medicineName: 'Azithromycin 500mg Tablets',
        genericName: 'Azithromycin Dihydrate',
        category: 'Antibiotic',
        currentStock: 220,
        unitType: 'Tablets',
        minimumSafetyBuffer: 180,
        dailyBurnRate: 15,
        projectedDaysRemaining: 14.6,
        batchNumber: 'AZI-3301',
        expiryDate: '2028-04-30',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 29.8,
        coldChainOk: true,
        status: 'Adequate',
      },
    ],
  },
  {
    id: 'PHC-AS-JENGRAI',
    code: 'PHC-AS-18009',
    name: 'PHC Jengraimukh (Majuli Island)',
    districtId: 'DIST-AS-MAJ',
    districtName: 'Majuli',
    stateCode: 'AS',
    stateName: 'Assam',
    tier: 'Primary Health Centre (PHC)',
    terrain: 'Riverine Island',
    coordinates: { lat: 27.012, lng: 94.225 },
    connectivity: 'Intermittent 2G',
    lastSyncTime: '15 mins ago',
    powerSource: 'Dual Solar Grid + Battery',
    activeAlertsCount: 2,
    footfall: {
      opdToday: 88,
      emergencyAdmissions: 4,
      feverOutbreakCases: 24,
      highRiskAntenatal: 6,
      historical7Days: [65, 70, 72, 78, 80, 85, 88],
    },
    beds: {
      generalTotal: 8,
      generalOccupied: 7,
      maternalTotal: 4,
      maternalOccupied: 3,
      oxygenTotal: 2,
      oxygenOccupied: 2,
      pediatricTotal: 3,
      pediatricOccupied: 2,
      emergencyTotal: 2,
      emergencyOccupied: 1,
    },
    personnel: [
      { role: 'Medical Officer (MBBS)', sanctioned: 2, present: 2, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Dr. Bhaskar Saikia' },
      { role: 'Staff Nurse', sanctioned: 3, present: 3, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Runjun Kalita' },
      { role: 'Auxiliary Nurse Midwife (ANM)', sanctioned: 5, present: 2, onFieldOutreach: 3, onLeave: 0, biometricVerified: true, shiftLead: 'Jonali Das' },
      { role: 'Pharmacist', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Dipen Borah' },
      { role: 'Lab Technician', sanctioned: 1, present: 1, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Pranjal Gogoi' },
    ],
    medicineInventory: [
      {
        id: 'MED-AS-01',
        medicineName: 'Artemether-Lumefantrine 20/120mg (Dispersible)',
        genericName: 'Pediatric ACT Antimalarial',
        category: 'Antimalarial',
        currentStock: 25,
        unitType: 'Tablets',
        minimumSafetyBuffer: 120,
        dailyBurnRate: 14,
        projectedDaysRemaining: 1.7,
        batchNumber: 'ACT-MAJ-801',
        expiryDate: '2027-12-15',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 24.2,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-AS-02',
        medicineName: 'Chlorine / Halazone Water Purification Tablets',
        genericName: 'Sodium Dichloroisocyanurate 67mg',
        category: 'Emergency / Antivenom',
        currentStock: 350,
        unitType: 'Tablets',
        minimumSafetyBuffer: 1000,
        dailyBurnRate: 120,
        projectedDaysRemaining: 2.9,
        batchNumber: 'WPT-1102',
        expiryDate: '2029-01-31',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 30°C',
        currentStorageTemp: 25.0,
        coldChainOk: true,
        status: 'Critical Deficit',
      },
      {
        id: 'MED-AS-03',
        medicineName: 'Ceftriaxone 1g Injection',
        genericName: 'Ceftriaxone Sodium Sterile Vials',
        category: 'Antibiotic',
        currentStock: 40,
        unitType: 'Vials',
        minimumSafetyBuffer: 80,
        dailyBurnRate: 8,
        projectedDaysRemaining: 5.0,
        batchNumber: 'CTX-AS-99',
        expiryDate: '2027-09-30',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 25°C',
        currentStorageTemp: 24.8,
        coldChainOk: true,
        status: 'Low Stock',
      },
    ],
  },
  {
    id: 'PHC-TN-MELUR',
    code: 'PHC-TN-33008',
    name: 'PHC Melur (Donor Hub)',
    districtId: 'DIST-TN-MDU',
    districtName: 'Madurai',
    stateCode: 'TN',
    stateName: 'Tamil Nadu',
    tier: 'Community Health Centre (CHC)',
    terrain: 'Plains',
    coordinates: { lat: 10.032, lng: 78.336 },
    connectivity: 'Online',
    lastSyncTime: '1 min ago',
    powerSource: 'Dual Solar Grid + Battery',
    activeAlertsCount: 0,
    footfall: {
      opdToday: 185,
      emergencyAdmissions: 8,
      feverOutbreakCases: 22,
      highRiskAntenatal: 14,
      historical7Days: [175, 180, 182, 178, 184, 182, 185],
    },
    beds: {
      generalTotal: 30,
      generalOccupied: 16,
      maternalTotal: 12,
      maternalOccupied: 7,
      oxygenTotal: 8,
      oxygenOccupied: 3,
      pediatricTotal: 8,
      pediatricOccupied: 4,
      emergencyTotal: 4,
      emergencyOccupied: 1,
    },
    personnel: [
      { role: 'Medical Officer (MBBS)', sanctioned: 4, present: 4, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'Dr. S. Sundaram' },
      { role: 'Staff Nurse', sanctioned: 8, present: 7, onFieldOutreach: 1, onLeave: 0, biometricVerified: true, shiftLead: 'V. Meenakshi' },
      { role: 'Auxiliary Nurse Midwife (ANM)', sanctioned: 10, present: 6, onFieldOutreach: 4, onLeave: 0, biometricVerified: true, shiftLead: 'K. Lakshmi' },
      { role: 'Pharmacist', sanctioned: 2, present: 2, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'P. Alagarsamy' },
      { role: 'Lab Technician', sanctioned: 2, present: 2, onFieldOutreach: 0, onLeave: 0, biometricVerified: true, shiftLead: 'T. Kannan' },
    ],
    medicineInventory: [
      {
        id: 'MED-TN-M-01',
        medicineName: 'Anti-Rabies Vaccine (Cell Culture)',
        genericName: 'Purified Chick Embryo Cell Vaccine',
        category: 'Vaccine',
        currentStock: 280,
        unitType: 'Vials',
        minimumSafetyBuffer: 60,
        dailyBurnRate: 6.2,
        projectedDaysRemaining: 45.1,
        batchNumber: 'ARV-TN-SURP-1',
        expiryDate: '2028-02-28',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 3.6,
        coldChainOk: true,
        status: 'Surplus',
      },
      {
        id: 'MED-TN-M-02',
        medicineName: 'Normal Saline (0.9% NaCl) 500ml',
        genericName: 'Sodium Chloride IV Infusion',
        category: 'IV Fluids',
        currentStock: 650,
        unitType: 'Bottles',
        minimumSafetyBuffer: 150,
        dailyBurnRate: 15,
        projectedDaysRemaining: 43.3,
        batchNumber: 'NS-MDU-88',
        expiryDate: '2028-10-15',
        coldChainRequired: false,
        idealTempRange: 'Ambient < 30°C',
        currentStorageTemp: 24.1,
        coldChainOk: true,
        status: 'Surplus',
      },
      {
        id: 'MED-TN-M-03',
        medicineName: 'Polyvalent Snake Antivenom (Lyophilized)',
        genericName: 'Anti-snake venom serum (Indian 4-species)',
        category: 'Emergency / Antivenom',
        currentStock: 140,
        unitType: 'Vials',
        minimumSafetyBuffer: 30,
        dailyBurnRate: 2.1,
        projectedDaysRemaining: 66.6,
        batchNumber: 'ASV-MDU-101',
        expiryDate: '2027-12-31',
        coldChainRequired: true,
        idealTempRange: '2°C - 8°C',
        currentStorageTemp: 4.0,
        coldChainOk: true,
        status: 'Surplus',
      },
    ],
  },
];

export const INITIAL_EARLY_WARNINGS: EarlyWarningAlert[] = [
  {
    id: 'ALERT-01',
    phcId: 'PHC-RJ-SHEO',
    phcName: 'PHC Sheo (Thar Desert)',
    district: 'Barmer',
    stateCode: 'RJ',
    severity: 'CRITICAL',
    title: 'Emergency Stock-out Imminent: IV Normal Saline (0.8 Days Remaining)',
    medicineOrResource: 'Normal Saline (0.9% NaCl) 500ml & ORS',
    currentBufferDays: 0.8,
    projectedStockoutHours: 19,
    surgeFactor: '+340% heatwave dehydration surge',
    reason: 'Severe extreme heatwave in western Rajasthan triggering massive dehydration admissions. Buffer exhausted.',
    recommendedAction: 'Execute emergency cross-district redistribution from Jodhpur District Medical Depot or dispatch refrigerated express carrier.',
    timestamp: '18 mins ago',
    acknowledged: false,
  },
  {
    id: 'ALERT-02',
    phcId: 'PHC-UP-CHAURI',
    phcName: 'PHC Chauri Chaura',
    district: 'Gorakhpur',
    stateCode: 'UP',
    severity: 'CRITICAL',
    title: 'Critical Pediatric Antibiotic Deficit: Ceftriaxone & Suspension (1.4 Days Remaining)',
    medicineOrResource: 'Ceftriaxone 1g Injection & Paracetamol',
    currentBufferDays: 1.4,
    projectedStockoutHours: 33,
    surgeFactor: '+260% Terai acute syndromic fever surge',
    reason: 'Post-monsoon seasonal spike in acute febrile illness among children. High daily burn rate.',
    recommendedAction: 'Trigger inter-district transfer from Varanasi Regional Warehouse and mobilize mobile CHC auxiliary supplies.',
    timestamp: '42 mins ago',
    acknowledged: false,
  },
  {
    id: 'ALERT-03',
    phcId: 'PHC-AS-JENGRAI',
    phcName: 'PHC Jengraimukh',
    district: 'Majuli',
    stateCode: 'AS',
    severity: 'CRITICAL',
    title: 'River Island Isolation Threat: Artemether & Water Purification Tabs (1.7 Days Remaining)',
    medicineOrResource: 'Artemether-Lumefantrine & Chlorine Dispersibles',
    currentBufferDays: 1.7,
    projectedStockoutHours: 40,
    surgeFactor: '+210% flood inundation waterborne threat',
    reason: 'Brahmaputra river water level rise threatening ferry logistics cut-off for Majuli sub-centres.',
    recommendedAction: 'Authorize emergency Medical Drone or river-patrol boat dispatch from Jorhat/Kamrup staging base.',
    timestamp: '1 hour ago',
    acknowledged: false,
  },
  {
    id: 'ALERT-04',
    phcId: 'PHC-TN-GUDALUR',
    phcName: 'PHC Gudalur',
    district: 'Nilgiris',
    stateCode: 'TN',
    severity: 'WARNING',
    title: 'Cold-Chain Buffer Alert: Anti-Rabies Vaccine (2.1 Days Remaining)',
    medicineOrResource: 'Anti-Rabies Vaccine (Cell Culture)',
    currentBufferDays: 2.1,
    projectedStockoutHours: 50,
    surgeFactor: '+180% wildlife/canine contact encounters',
    reason: 'Remote forest-fringe community dog-bite encounters increasing. Local buffer depleted.',
    recommendedAction: 'Dispatch refrigerated van from PHC Melur (Madurai hub with 280 surplus vials).',
    timestamp: '2 hours ago',
    acknowledged: true,
  },
  {
    id: 'ALERT-05',
    phcId: 'PHC-MH-BHOR',
    phcName: 'PHC Bhor',
    district: 'Pune',
    stateCode: 'MH',
    severity: 'WARNING',
    title: 'Buffer Depletion Warning: Polyvalent Snake Antivenom (4.1 Days Remaining)',
    medicineOrResource: 'Polyvalent Snake Antivenom',
    currentBufferDays: 4.1,
    projectedStockoutHours: 98,
    surgeFactor: '+140% monsoon agricultural harvesting exposure',
    reason: 'Monsoon paddy cultivation season leads to elevated viper envenomation cases in Western Ghats foothills.',
    recommendedAction: 'Pre-allocate 20 vials from Pune District Civil Hospital medical depot.',
    timestamp: '3 hours ago',
    acknowledged: true,
  },
];

export const INITIAL_TRANSFERS: RedistributionTransfer[] = [
  {
    id: 'TR-2026-9041',
    transferNumber: 'TR-MH-PUN-091',
    fromPhcId: 'PHC-MH-NRYN',
    fromPhcName: 'PHC Narayangaon Depot',
    fromDistrict: 'Pune',
    toPhcId: 'PHC-MH-BHOR',
    toPhcName: 'PHC Bhor',
    toDistrict: 'Pune',
    medicineName: 'Normal Saline (0.9% NaCl) 500ml',
    category: 'IV Fluids',
    quantityUnits: 150,
    transportMode: 'District Health Express Truck',
    distanceKm: 88,
    etaHours: 2.2,
    status: 'In Transit',
    currentTempReading: 22.4,
    authSignToken: 'DSC-IN-MOHFW-MH-8819',
    tamperProofHash: 'a89c4d92efb10293ec492048f8102934bb61e892c901ef4',
    createdAt: '1 hr 15m ago',
  },
  {
    id: 'TR-2026-9042',
    transferNumber: 'TR-TN-MDU-044',
    fromPhcId: 'PHC-TN-MELUR',
    fromPhcName: 'PHC Melur',
    fromDistrict: 'Madurai',
    toPhcId: 'PHC-TN-GUDALUR',
    toPhcName: 'PHC Gudalur',
    toDistrict: 'Nilgiris',
    medicineName: 'Anti-Rabies Vaccine (Cell Culture)',
    category: 'Vaccine',
    quantityUnits: 80,
    transportMode: 'Refrigerated Cold Chain Van',
    distanceKm: 210,
    etaHours: 5.1,
    status: 'Cold Chain Verified',
    currentTempReading: 3.8,
    authSignToken: 'DSC-IN-MOHFW-TN-4190',
    tamperProofHash: 'e71b2890cd4910293ec482019fe82049104c9902ba12998',
    createdAt: '2 hrs ago',
  },
  {
    id: 'TR-2026-9043',
    transferNumber: 'TR-UP-VNS-112',
    fromPhcId: 'PHC-UP-SEVA',
    fromPhcName: 'PHC Sevapuri Depot',
    fromDistrict: 'Varanasi',
    toPhcId: 'PHC-UP-CHAURI',
    toPhcName: 'PHC Chauri Chaura',
    toDistrict: 'Gorakhpur',
    medicineName: 'Ceftriaxone 1g Injection',
    category: 'Antibiotic',
    quantityUnits: 200,
    transportMode: 'District Health Express Truck',
    distanceKm: 195,
    etaHours: 4.0,
    status: 'Authorized',
    currentTempReading: 23.8,
    authSignToken: 'DSC-IN-MOHFW-UP-6602',
    tamperProofHash: 'b44120938f0912ec901239aa8123901fc88902183c9012e',
    createdAt: '35 mins ago',
  },
];

export const OUTBREAK_SCENARIOS: OutbreakScenario[] = [
  {
    id: 'SCENARIO-DENGUE',
    name: 'Monsoon Dengue & Vector Surge',
    tagline: 'Western Ghats & Southern Coastal Corridors',
    affectedStates: ['MH', 'TN', 'KL'],
    affectedCategories: ['IV Fluids', 'Emergency / Antivenom', 'Antibiotic'],
    footfallMultiplier: 2.4,
    burnRateMultiplier: 2.8,
    description: 'Intense post-monsoon water logging leading to 240% increase in Dengue shock cases, acute fever footfall, and high demand for IV crystalloids & paracetamol infusions.',
  },
  {
    id: 'SCENARIO-HEATWAVE',
    name: 'Thar Desert Extreme Heatwave',
    tagline: 'Western Rajasthan & Northern Arid Belt',
    affectedStates: ['RJ', 'UP'],
    affectedCategories: ['IV Fluids'],
    footfallMultiplier: 2.8,
    burnRateMultiplier: 3.5,
    description: 'Temperatures breaching 48.5°C across Barmer, Jodhpur, and Sitapur. Severe heat-stroke collapse, acute renal dehydration, requiring emergency replenishment of Normal Saline & ORS buffers.',
  },
  {
    id: 'SCENARIO-FLOOD',
    name: 'Brahmaputra Basin Flood Emergency',
    tagline: 'Riverine Assam & Coastal Odisha Islands',
    affectedStates: ['AS', 'OD'],
    affectedCategories: ['Antimalarial', 'Antibiotic', 'IV Fluids', 'Emergency / Antivenom'],
    footfallMultiplier: 2.2,
    burnRateMultiplier: 3.1,
    description: 'Widespread inundation cutting off river island PHCs like Majuli. Submersion elevates waterborne diarrheal outbreaks, leptospirosis, and snake envenomation threats.',
  },
  {
    id: 'SCENARIO-TERAI-AES',
    name: 'Terai Belt Acute Encephalitis Syndrome',
    tagline: 'Eastern Uttar Pradesh & Northern Plains',
    affectedStates: ['UP', 'AS'],
    affectedCategories: ['Antibiotic', 'Vaccine', 'Emergency / Antivenom'],
    footfallMultiplier: 2.6,
    burnRateMultiplier: 2.9,
    description: 'Seasonal surge in acute neuro-infections among pediatric admissions in Gorakhpur and surrounding river plains. Demands rapid ICU bed turnover and cephalosporin buffers.',
  },
];

export const INITIAL_FEDERATED_ROUND: FederatedTrainingRound = {
  roundNumber: 18,
  globalAccuracy: 94.8,
  globalLoss: 0.038,
  totalClientNodes: 7,
  privacyBudgetUsedEpsilon: 1.2,
  deltaPrivacy: 1e-5,
  timestamp: 'Today, 14:30 IST',
  status: 'Completed',
  clientStates: [
    { stateCode: 'MH', stateName: 'Maharashtra', localSamples: 48200, localEpochs: 5, localLoss: 0.042, gradientNorm: 0.018, privacyNoiseAdded: 0.052, weightDivergencePercent: 2.1, status: 'Aggregated' },
    { stateCode: 'UP', stateName: 'Uttar Pradesh', localSamples: 72100, localEpochs: 5, localLoss: 0.058, gradientNorm: 0.024, privacyNoiseAdded: 0.055, weightDivergencePercent: 4.8, status: 'Aggregated' },
    { stateCode: 'TN', stateName: 'Tamil Nadu', localSamples: 39500, localEpochs: 5, localLoss: 0.029, gradientNorm: 0.014, privacyNoiseAdded: 0.048, weightDivergencePercent: 1.6, status: 'Aggregated' },
    { stateCode: 'KL', stateName: 'Kerala', localSamples: 24800, localEpochs: 5, localLoss: 0.021, gradientNorm: 0.011, privacyNoiseAdded: 0.045, weightDivergencePercent: 1.2, status: 'Aggregated' },
    { stateCode: 'RJ', stateName: 'Rajasthan', localSamples: 36400, localEpochs: 5, localLoss: 0.062, gradientNorm: 0.026, privacyNoiseAdded: 0.058, weightDivergencePercent: 5.2, status: 'Aggregated' },
    { stateCode: 'AS', stateName: 'Assam', localSamples: 19800, localEpochs: 5, localLoss: 0.067, gradientNorm: 0.029, privacyNoiseAdded: 0.061, weightDivergencePercent: 6.4, status: 'Aggregated' },
    { stateCode: 'OD', stateName: 'Odisha', localSamples: 28900, localEpochs: 5, localLoss: 0.048, gradientNorm: 0.019, privacyNoiseAdded: 0.051, weightDivergencePercent: 3.1, status: 'Aggregated' },
  ],
  aiSynthesis: {
    summary: 'Federated aggregation completed successfully across all 7 state clusters, driving global demand forecasting accuracy to 94.8% without centralizing raw health records.',
    stateEpidemiologicalDrift: 'Rajasthan exhibited elevated gradient shifts on fluid and electrolyte dynamics, while Assam and Uttar Pradesh drove antibiotic and pediatric suspension predictive weights.',
    privacyPreservationProof: 'Differential Privacy noise calibrated at sigma=0.052 bounds epsilon to 1.2 (delta=10^-5), meeting stringent statutory health information privacy standards under Indian DPDP Act 2023.',
    modelGeneralizationGain: 'Cross-state aggregation reduces out-of-distribution stock-out prediction errors by 38% compared to isolated single-state forecasting models.',
    recommendedModelActions: [
      'Synchronize updated global weights to all 31,480 edge PHC instances',
      'Maintain elevated sampling frequency on flood-prone Eastern coastal nodes',
      'Schedule Round 19 post-monsoon calibration in 72 hours'
    ]
  }
};
